// AUTO-GENERATED by scripts/generate-engine-fixtures.mjs. Do not edit by hand.
// Regenerate with: npm run generate:engine-fixtures
// Expected Stockfish replies (UCI) for the curated black-to-move positions per
// difficulty tier. See specs/001-chess-vs-computer/research.md (R3).

import type { Difficulty } from "../../src/game/types";

export interface EngineMoveFixture {
  id: string;
  fen: string;
  moves: Record<Difficulty, string | null>;
}

export const ENGINE_MOVES: EngineMoveFixture[] = [
  {
    "id": "kiwipete",
    "fen": "r3k2r/p1ppqpb1/Bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPB1PPP/R3K2R b KQkq - 0 1",
    "moves": {
      "easy": "b4c3",
      "medium": "h3g2",
      "hard": "b4c3"
    }
  },
  {
    "id": "rook-endgame",
    "fen": "8/2p5/3p4/KP5r/5R1k/8/4P1P1/8 b - - 0 1",
    "moves": {
      "easy": "h4g3",
      "medium": "h4g5",
      "hard": "h4g3"
    }
  }
];

export function expectedEngineMove(id: string, difficulty: Difficulty): string | null {
  const entry = ENGINE_MOVES.find((item) => item.id === id);
  if (!entry) throw new Error(`No engine fixture for position "${id}"`);
  return entry.moves[difficulty];
}
